version: 2

jobs:
  build:
    environment:
      DOCKER_BUILDKIT: 1
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: build image
          command: docker build -t bungoume/log-sender .
      - run:
          name: Test
          command: |
            docker run -d --name log-sender -e TO_HOST=192.0.2.0 bungoume/log-sender
      - run:
          name: check boot log
          command: |
            # waiting to boot fluentd
            sleep 5
            docker logs log-sender
      - run:
          name: Test listen at TCP10224
          command: |
            docker exec -t log-sender sh -c "nc -vz -w5 localhost 10224"
      - run:
          name: Send sample log
          command: |
            docker exec -t log-sender sh -c "echo '{\"client_ip\":\"93.184.216.34\",\"upstream_taken_time\":0.01}' | fluent-cat -p 10224 access.nginx"
      - run:
          name: Check send log
          command: docker logs log-sender
          when: always
